services:
  - type: web
    name: apollo-kotlin-demo-server
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./server/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        generateValue: true
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1