{
  "formatVersion": "1.1",
  "component": {
    "url": "../../apollo-runtime/5.0.0-alpha.local-SNAPSHOT/apollo-runtime-5.0.0-alpha.local-SNAPSHOT.module",
    "group": "com.apollographql.apollo",
    "module": "apollo-runtime",
    "version": "5.0.0-alpha.local-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "5.0.0-alpha.local-SNAPSHOT"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-mpp-utils",
          "version": {
            "requires": "5.0.0-alpha.local-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-wasm-js-5.0.0-alpha.local-SNAPSHOT.klib",
          "url": "apollo-runtime-wasm-js-5.0.0-alpha.local-SNAPSHOT.klib",
          "size": 321864,
          "sha512": "9edb21026266e4b8cee34cd410a81a6a5eea32e23893d6d4763ac2d63efd509e8ea4c2a63c920996e72544477d9391ad02332788aaf95a5c5b036d755affb51c",
          "sha256": "8a9ddb0a6c51a364670ba1cef3ab2c30f7cebd8c3c144bed3ebf73de1bbf8175",
          "sha1": "dca7efa63a3ed50464c338dd79ce9aedf873c0fc",
          "md5": "dac75457f0cc3e0845201a169cce1896"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-api",
          "version": {
            "requires": "5.0.0-alpha.local-SNAPSHOT"
          }
        },
        {
          "group": "com.apollographql.apollo",
          "module": "apollo-mpp-utils",
          "version": {
            "requires": "5.0.0-alpha.local-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "apollo-runtime-wasm-js-5.0.0-alpha.local-SNAPSHOT.klib",
          "url": "apollo-runtime-wasm-js-5.0.0-alpha.local-SNAPSHOT.klib",
          "size": 321864,
          "sha512": "9edb21026266e4b8cee34cd410a81a6a5eea32e23893d6d4763ac2d63efd509e8ea4c2a63c920996e72544477d9391ad02332788aaf95a5c5b036d755affb51c",
          "sha256": "8a9ddb0a6c51a364670ba1cef3ab2c30f7cebd8c3c144bed3ebf73de1bbf8175",
          "sha1": "dca7efa63a3ed50464c338dd79ce9aedf873c0fc",
          "md5": "dac75457f0cc3e0845201a169cce1896"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "apollo-runtime-wasm-js-5.0.0-alpha.local-SNAPSHOT-sources.jar",
          "url": "apollo-runtime-wasm-js-5.0.0-alpha.local-SNAPSHOT-sources.jar",
          "size": 82480,
          "sha512": "3b1f94487b6dea1520c2e1b320812c7ad75969f56b104e74649f88523f006f00bb0dafdc4b68833b28d11d00774216e277496197ee89ffe65783dd98bd77b4ad",
          "sha256": "1b0cc9f254f93399979047efc76e98b598d802c9b63e722bee61dccef7a91953",
          "sha1": "80137882b6200caf1a9a356574ce17354d64b707",
          "md5": "2839b47a43d9ec699e1881d22b74c9db"
        }
      ]
    }
  ]
}
